name: SocialDistancing
author: superjoy0502
version: ${version}
main: io.github.superjoy0502.socialdistancing.SocialDistancingPlugin
api-version: 1.17
libraries:
  - io.github.monun:tap:4.1.1
  - io.github.monun:kommand:2.2.0